Attribute VB_Name = "Module1"
Option Explicit

Public state As String
Public statecode As String
Public FZNo As String
Public FZClass As String
Public FZ3X5PHPN As String
Public FZ3X5PHPrice As String
Public FZ3X5PHFPN As String
Public FZ3X5PHFPrice As String
Public FZ4X6PHPN As String
Public FZ4X6PHPrice As String
Public FZ4X6PHFPN As String
Public FZ4X6PHFPrice As String
Public FZ7FtHWPN As String
Public FZ7FtHWPrice As String
Public FZ8FtHWPN As String
Public FZ8FtHWPrice As String
Public FZ9FtHWPN As String
Public FZ9FtHWPrice As String
Public BaseSKU As String

Public PRSETPH357SKU As String
Public PRSETPH357MPN As String
Public PRSETPH357Price As String
Public PRSETPH357Cost As String

Public PRSETPHF357SKU As String
Public PRSETPHF357MPN As String
Public PRSETPHF357Price As String
Public PRSETPHF357Cost As String

Public PRSETPH358SKU As String
Public PRSETPH358MPN As String
Public PRSETPH358Price As String
Public PRSETPH358Cost As String

Public PRSETPHF358SKU As String
Public PRSETPHF358MPN As String
Public PRSETPHF358Price As String
Public PRSETPHF358Cost As String

Public PRSETPH469SKU As String
Public PRSETPH469MPN As String
Public PRSETPH469Price As String
Public PRSETPH469Cost As String

Public PRSETPHF469SKU As String
Public PRSETPHF469MPN As String
Public PRSETPHF469Price As String
Public PRSETPHF469Cost As String

Public PRSETPHImage As String
Public PRSETPHFImage As String
Public PHFFlagImage As String
Public HWImage As String
Public ImageDesc As String
Public PageTitle As String
Public Category As String

Sub RunThis()
Dim sourcebook As Workbook
Set sourcebook = Workbooks.Open("S:\Web Site Files\Flags\State Flags\Presentation Sets\State_Flag_Presentation_Set_Worksheet.xlsx")
Dim sourcesheet As Worksheet
Set sourcesheet = sourcebook.Worksheets("Sheet1")
'Dim range As range                         ' why use range anyway?? also, that is a reserved word!!
'Set range = sourcesheet.range("A2:EM57")   ' why wider thatn actual data area???
Dim newwb As Workbook
Set newwb = Workbooks.Add
newwb.SaveAs Filename:="S:\Web Site Files\Flags\State Flags\Presentation Sets\VBA\Test1.xlsx", FileFormat:=xlWorkbookDefault
Dim newsheet As Worksheet
Set newsheet = newwb.ActiveSheet
Call WriteHeaderRow(newsheet)
' process input sheet, rows 2 through 57
Dim i As Long  ' index into state list 1 = first (on row 2)
For i = 1 To 57
  Call ReadStateRow(sourcesheet, i + 1)  ' first state on row 2 of input sheet
  ' for the following, pass first row of each set of 13 rows per product
  Call WriteProductRow(newsheet, ((i - 1) * 13) + 2) ' first state to row 2, next to row 15, etc.
  Call FlagSKUs(newsheet, ((i - 1) * 13) + 2)
  Call FlagSKURules(newsheet, ((i - 1) * 13) + 2)
Next
newwb.Save
MsgBox "Done"
End Sub

Sub WriteHeaderRow(ns As Worksheet)
ns.Cells(1, 1) = "Item Type"
ns.Cells(1, 2) = "Product ID"
ns.Cells(1, 3) = "Sort Order"
ns.Cells(1, 4) = "Product Name"
ns.Cells(1, 5) = "Product Type"
ns.Cells(1, 6) = "Product Code/SKU"
ns.Cells(1, 7) = "Bin Picking Number"
ns.Cells(1, 8) = "Origin Locations"
ns.Cells(1, 9) = "Shipping Groups"
ns.Cells(1, 10) = "Dimensional Rules"
ns.Cells(1, 11) = "Brand Name"
ns.Cells(1, 12) = "Option Set"
ns.Cells(1, 13) = "Option Set Align"
ns.Cells(1, 14) = "Product Description"
ns.Cells(1, 15) = "Price"
ns.Cells(1, 16) = "Cost Price"
ns.Cells(1, 17) = "Retail Price"
ns.Cells(1, 18) = "Sale Price"
ns.Cells(1, 19) = "Fixed Shipping Cost"
ns.Cells(1, 20) = "Free Shipping"
ns.Cells(1, 21) = "Product Warranty"
ns.Cells(1, 22) = "Product Weight"
ns.Cells(1, 23) = "Product Width"
ns.Cells(1, 24) = "Product Height"
ns.Cells(1, 25) = "Product Depth"
ns.Cells(1, 26) = "Allow Purchases?"
ns.Cells(1, 27) = "Product Visible?"
ns.Cells(1, 28) = "Product Availability"
ns.Cells(1, 29) = "Track Inventory"
ns.Cells(1, 30) = "Current Stock Level"
ns.Cells(1, 31) = "Low Stock Level"
ns.Cells(1, 32) = "Category"
ns.Cells(1, 33) = "Product Image File - 1"
ns.Cells(1, 34) = "Product Image URL - 1"
ns.Cells(1, 35) = "Product Image ID - 1"
ns.Cells(1, 36) = "Product Image File - 1"
ns.Cells(1, 37) = "Product Image Description - 1"
ns.Cells(1, 38) = "Product Image Is Thumbnail - 1"
ns.Cells(1, 39) = "Product Image Sort - 1"
ns.Cells(1, 40) = "Product Image File - 2"
ns.Cells(1, 41) = "Product Image URL - 2"
ns.Cells(1, 42) = "Product Image ID - 2"
ns.Cells(1, 43) = "Product Image File - 2"
ns.Cells(1, 44) = "Product Image Description - 2"
ns.Cells(1, 45) = "Product Image Is Thumbnail - 2"
ns.Cells(1, 46) = "Product Image Sort - 2"
ns.Cells(1, 47) = "Product Image File - 3"
ns.Cells(1, 48) = "Product Image URL - 3"
ns.Cells(1, 49) = "Product Image ID - 3"
ns.Cells(1, 50) = "Product Image File - 3"
ns.Cells(1, 51) = "Product Image Description - 3"
ns.Cells(1, 52) = "Product Image Is Thumbnail - 3"
ns.Cells(1, 53) = "Product Image Sort - 3"
ns.Cells(1, 54) = "Search Keywords"
ns.Cells(1, 55) = "Page Title"
ns.Cells(1, 56) = "Meta Keywords"
ns.Cells(1, 57) = "Meta Description"
ns.Cells(1, 58) = "Product Condition"
ns.Cells(1, 59) = "Show Product Condition?"
ns.Cells(1, 60) = "Product Tax Class"
ns.Cells(1, 61) = "Manufacturer Part Number"
ns.Cells(1, 62) = "Product UPC/EAN"
ns.Cells(1, 63) = "Product URL"
ns.Cells(1, 64) = "Redirect Old URL?"
ns.Cells(1, 65) = "GPS Global Trade Item Number"
ns.Cells(1, 66) = "GPS Color"
ns.Cells(1, 67) = "GPS Item Group ID"
ns.Cells(1, 68) = "GPS Category"
ns.Cells(1, 69) = "Product Custom Fields"
End Sub

Sub ReadStateRow(ss As Worksheet, rownumber As Long)
state = ss.Cells(rownumber, 1)
statecode = ss.Cells(rownumber, 2)
FZNo = ss.Cells(rownumber, 3)
FZClass = ss.Cells(rownumber, 4)
FZ3X5PHPN = ss.Cells(rownumber, 5)
FZ3X5PHPrice = ss.Cells(rownumber, 6)
FZ3X5PHFPN = ss.Cells(rownumber, 7)
FZ3X5PHFPrice = ss.Cells(rownumber, 8)
FZ4X6PHPN = ss.Cells(rownumber, 9)
FZ4X6PHPrice = ss.Cells(rownumber, 10)
FZ4X6PHFPN = ss.Cells(rownumber, 11)
FZ4X6PHFPrice = ss.Cells(rownumber, 12)
FZ7FtHWPN = ss.Cells(rownumber, 13)
FZ7FtHWPrice = ss.Cells(rownumber, 14)
FZ8FtHWPN = ss.Cells(rownumber, 15)
FZ8FtHWPrice = ss.Cells(rownumber, 16)
FZ9FtHWPN = ss.Cells(rownumber, 17)
FZ9FtHWPrice = ss.Cells(rownumber, 18)
BaseSKU = ss.Cells(rownumber, 19)
PRSETPH357SKU = ss.Cells(rownumber, 20)
PRSETPH357Cost = ss.Cells(rownumber, 21)
PRSETPH357Price = ss.Cells(rownumber, 22)
PRSETPH357MPN = ss.Cells(rownumber, 23)
PRSETPHF357SKU = ss.Cells(rownumber, 24)
PRSETPHF357Cost = ss.Cells(rownumber, 25)
PRSETPHF357Price = ss.Cells(rownumber, 26)
PRSETPHF357MPN = ss.Cells(rownumber, 27)
PRSETPH358SKU = ss.Cells(rownumber, 28)
PRSETPH358Cost = ss.Cells(rownumber, 29)
PRSETPH358Price = ss.Cells(rownumber, 30)
PRSETPH358MPN = ss.Cells(rownumber, 31)
PRSETPHF358SKU = ss.Cells(rownumber, 32)
PRSETPHF358Cost = ss.Cells(rownumber, 33)
PRSETPHF358Price = ss.Cells(rownumber, 34)
PRSETPHF358MPN = ss.Cells(rownumber, 35)
PRSETPH469SKU = ss.Cells(rownumber, 36)
PRSETPH469Cost = ss.Cells(rownumber, 37)
PRSETPH469Price = ss.Cells(rownumber, 38)
PRSETPH469MPN = ss.Cells(rownumber, 39)
PRSETPHF469SKU = ss.Cells(rownumber, 40)
PRSETPHF469Cost = ss.Cells(rownumber, 41)
PRSETPHF469Price = ss.Cells(rownumber, 42)
PRSETPHF469MPN = ss.Cells(rownumber, 43)
PRSETPHImage = ss.Cells(rownumber, 44)
PRSETPHFImage = ss.Cells(rownumber, 45)
PHFFlagImage = ss.Cells(rownumber, 46)
HWImage = ss.Cells(rownumber, 47)
ImageDesc = ss.Cells(rownumber, 48)
PageTitle = ss.Cells(rownumber, 49)
Category = ss.Cells(rownumber, 50)
End Sub

Sub WriteProductRow(ns As Worksheet, ra As Long)
ns.Cells(ra, 1) = "Product"
ns.Cells(ra, 2) = ""
ns.Cells(ra, 3) = "0"
ns.Cells(ra, 4) = state + " Deluxe Indoor Presentation Set with Oak Pole, Gold Base and Hardware (Open Market)"
ns.Cells(ra, 5) = "P"
ns.Cells(ra, 6) = BaseSKU
ns.Cells(ra, 7) = ""
ns.Cells(ra, 8) = ""
ns.Cells(ra, 9) = ""
ns.Cells(ra, 10) = ""
ns.Cells(ra, 11) = ""
ns.Cells(ra, 12) = "Oak Presentation Set Options"
ns.Cells(ra, 13) = "Right"
ns.Cells(ra, 14) = ""
ns.Cells(ra, 15) = "0.00"
ns.Cells(ra, 16) = "0.00"
ns.Cells(ra, 17) = "0.00"
ns.Cells(ra, 18) = "0.00"
ns.Cells(ra, 19) = "0"
ns.Cells(ra, 20) = "N"
ns.Cells(ra, 21) = ""
ns.Cells(ra, 22) = "25"
ns.Cells(ra, 23) = "53"
ns.Cells(ra, 24) = "13"
ns.Cells(ra, 25) = "6"
ns.Cells(ra, 26) = "Y"
ns.Cells(ra, 27) = "Y"
ns.Cells(ra, 28) = ""
ns.Cells(ra, 29) = "none"
ns.Cells(ra, 30) = "0"
ns.Cells(ra, 31) = "0"
ns.Cells(ra, 32) = "Flags/State & U.S. Territory Flags/" + state + " Flags/Indoor" + state + " Flags;Flagpoles/Indoor Flagpoles/Presentation Flagpole Sets/State Indoor & Parade Set"
ns.Cells(ra, 33) = "https://emflag.com/content/Flags/State/Indoor/Presentation%20Sets/PRSET-" + state + "-PHF.png"
ns.Cells(ra, 34) = "https://emflag.com/content/Flags/State/Indoor/Presentation%20Sets/PRSET-" + state + "-PHF.png"
ns.Cells(ra, 35) = ""
ns.Cells(ra, 36) = ""
ns.Cells(ra, 37) = "Deluxe Indoor and Parade " + state + "Flag Presentation Set"
ns.Cells(ra, 38) = "Y"
ns.Cells(ra, 39) = "1"
ns.Cells(ra, 40) = ""
ns.Cells(ra, 41) = ""
ns.Cells(ra, 42) = ""
ns.Cells(ra, 43) = ""
ns.Cells(ra, 44) = ""
ns.Cells(ra, 45) = ""
ns.Cells(ra, 46) = ""
ns.Cells(ra, 47) = ""
ns.Cells(ra, 48) = ""
ns.Cells(ra, 49) = ""
ns.Cells(ra, 50) = ""
ns.Cells(ra, 51) = ""
ns.Cells(ra, 52) = ""
ns.Cells(ra, 53) = ""
ns.Cells(ra, 54) = "Deluxe Indoor and Parade " + state + "Flag Presentation Set"
ns.Cells(ra, 55) = "Shop " + state + " Indoor and Parade Presentation Set - Made in USA"
ns.Cells(ra, 56) = "Meta Keywords"
ns.Cells(ra, 57) = "Meta Description"
ns.Cells(ra, 58) = "New"
ns.Cells(ra, 59) = "N"
ns.Cells(ra, 60) = "Default Tax Class"
ns.Cells(ra, 61) = ""
ns.Cells(ra, 62) = ""
ns.Cells(ra, 63) = ""
ns.Cells(ra, 64) = ""
ns.Cells(ra, 65) = ""
ns.Cells(ra, 66) = ""
ns.Cells(ra, 67) = ""
ns.Cells(ra, 68) = ""
ns.Cells(ra, 69) = ""
End Sub

Sub FlagSKUs(ns As Worksheet, ra As Long)  ' ra is first row of each set of product data

'12inX18inHG SKU - product row 2
ra = ra + 1
ns.Cells(ra, 1) = "SKU"
ns.Cells(ra, 2) = ""
ns.Cells(ra, 3) = ""
ns.Cells(ra, 4) = "[RT]Finishing Options=Pole Hem Only,[RT]Flag and Pole Size=3' X 5' Flag with 7' Oak Pole"
ns.Cells(ra, 5) = ""
ns.Cells(ra, 6) = PRSETPH357SKU
ns.Cells(ra, 7) = "FlagZone"
ns.Cells(ra, 8) = "FlagZone"
ns.Cells(ra, 9) = ""
ns.Cells(ra, 10) = ""
ns.Cells(ra, 11) = "FlagZone"
ns.Cells(ra, 12) = ""
ns.Cells(ra, 13) = ""
ns.Cells(ra, 14) = ""
ns.Cells(ra, 15) = ""
ns.Cells(ra, 16) = PRSETPH357Cost
ns.Cells(ra, 17) = ""
ns.Cells(ra, 18) = ""
ns.Cells(ra, 19) = ""
ns.Cells(ra, 20) = "N"
ns.Cells(ra, 21) = ""
ns.Cells(ra, 22) = "18"
ns.Cells(ra, 23) = "53"
ns.Cells(ra, 24) = "13"
ns.Cells(ra, 25) = "6"
ns.Cells(ra, 26) = ""
ns.Cells(ra, 27) = ""
ns.Cells(ra, 28) = ""
ns.Cells(ra, 29) = ""
ns.Cells(ra, 30) = ""
ns.Cells(ra, 31) = ""
ns.Cells(ra, 32) = ""
ns.Cells(ra, 33) = ""
ns.Cells(ra, 34) = ""
ns.Cells(ra, 35) = ""
ns.Cells(ra, 36) = ""
ns.Cells(ra, 37) = ""
ns.Cells(ra, 38) = ""
ns.Cells(ra, 39) = ""
ns.Cells(ra, 40) = ""
ns.Cells(ra, 41) = ""
ns.Cells(ra, 42) = ""
ns.Cells(ra, 43) = ""
ns.Cells(ra, 44) = ""
ns.Cells(ra, 45) = ""
ns.Cells(ra, 46) = ""
ns.Cells(ra, 47) = ""
ns.Cells(ra, 48) = ""
ns.Cells(ra, 49) = ""
ns.Cells(ra, 50) = ""
ns.Cells(ra, 51) = ""
ns.Cells(ra, 52) = ""
ns.Cells(ra, 53) = ""
ns.Cells(ra, 54) = ""
ns.Cells(ra, 55) = ""
ns.Cells(ra, 56) = ""
ns.Cells(ra, 57) = ""
ns.Cells(ra, 58) = ""
ns.Cells(ra, 59) = ""
ns.Cells(ra, 60) = ""
ns.Cells(ra, 61) = PRSETPH357MPN
ns.Cells(ra, 62) = ""
ns.Cells(ra, 63) = ""
ns.Cells(ra, 64) = ""
ns.Cells(ra, 65) = ""
ns.Cells(ra, 66) = ""
ns.Cells(ra, 67) = ""
ns.Cells(ra, 68) = ""
ns.Cells(ra, 69) = ""

'2X3 HG SKU  - product row 3
ra = ra + 1
ns.Cells(ra, 1) = "SKU"
ns.Cells(ra, 2) = ""
ns.Cells(ra, 3) = ""
ns.Cells(ra, 4) = "[RT]Finishing Options=Pole Hem & Fringe,[RT]Flag and Pole Size=3' X 5' Flag with 7' Oak Pole"
ns.Cells(ra, 5) = ""
ns.Cells(ra, 6) = PRSETPHF357SKU
ns.Cells(ra, 7) = "FlagZone"
ns.Cells(ra, 8) = "FlagZone"
ns.Cells(ra, 9) = ""
ns.Cells(ra, 10) = ""
ns.Cells(ra, 11) = "FlagZone"
ns.Cells(ra, 12) = ""
ns.Cells(ra, 13) = ""
ns.Cells(ra, 14) = ""
ns.Cells(ra, 15) = ""
ns.Cells(ra, 16) = PRSETPHF357Cost
ns.Cells(ra, 17) = ""
ns.Cells(ra, 18) = ""
ns.Cells(ra, 19) = ""
ns.Cells(ra, 20) = "N"
ns.Cells(ra, 21) = ""
ns.Cells(ra, 22) = "18"
ns.Cells(ra, 23) = "53"
ns.Cells(ra, 24) = "13"
ns.Cells(ra, 25) = "6"
ns.Cells(ra, 26) = ""
ns.Cells(ra, 27) = ""
ns.Cells(ra, 28) = ""
ns.Cells(ra, 29) = ""
ns.Cells(ra, 30) = ""
ns.Cells(ra, 31) = ""
ns.Cells(ra, 32) = ""
ns.Cells(ra, 33) = ""
ns.Cells(ra, 34) = ""
ns.Cells(ra, 35) = ""
ns.Cells(ra, 36) = ""
ns.Cells(ra, 37) = ""
ns.Cells(ra, 38) = ""
ns.Cells(ra, 39) = ""
ns.Cells(ra, 40) = ""
ns.Cells(ra, 41) = ""
ns.Cells(ra, 42) = ""
ns.Cells(ra, 43) = ""
ns.Cells(ra, 44) = ""
ns.Cells(ra, 45) = ""
ns.Cells(ra, 46) = ""
ns.Cells(ra, 47) = ""
ns.Cells(ra, 48) = ""
ns.Cells(ra, 49) = ""
ns.Cells(ra, 50) = ""
ns.Cells(ra, 51) = ""
ns.Cells(ra, 52) = ""
ns.Cells(ra, 53) = ""
ns.Cells(ra, 54) = ""
ns.Cells(ra, 55) = ""
ns.Cells(ra, 56) = ""
ns.Cells(ra, 57) = ""
ns.Cells(ra, 58) = ""
ns.Cells(ra, 59) = ""
ns.Cells(ra, 60) = ""
ns.Cells(ra, 61) = PRSETPHF357MPN
ns.Cells(ra, 62) = ""
ns.Cells(ra, 63) = ""
ns.Cells(ra, 64) = ""
ns.Cells(ra, 65) = ""
ns.Cells(ra, 66) = ""
ns.Cells(ra, 67) = ""
ns.Cells(ra, 68) = ""
ns.Cells(ra, 69) = ""

'3X5 HG SKU  - product row 4
ra = ra + 1
ns.Cells(ra, 1) = "SKU"
ns.Cells(ra, 2) = ""
ns.Cells(ra, 3) = ""
ns.Cells(ra, 4) = "[RT]Finishing Options=Pole Hem Only,[RT]Flag and Pole Size=3' X 5' Flag with 8' Oak Pole"
ns.Cells(ra, 5) = ""
ns.Cells(ra, 6) = PRSETPH358SKU
ns.Cells(ra, 7) = "FlagZone"
ns.Cells(ra, 8) = "FlagZone"
ns.Cells(ra, 9) = ""
ns.Cells(ra, 10) = ""
ns.Cells(ra, 11) = "FlagZone"
ns.Cells(ra, 12) = ""
ns.Cells(ra, 13) = ""
ns.Cells(ra, 14) = ""
ns.Cells(ra, 15) = ""
ns.Cells(ra, 16) = PRSETPH358Cost
ns.Cells(ra, 17) = ""
ns.Cells(ra, 18) = ""
ns.Cells(ra, 19) = ""
ns.Cells(ra, 20) = "N"
ns.Cells(ra, 21) = ""
ns.Cells(ra, 22) = "18"
ns.Cells(ra, 23) = "53"
ns.Cells(ra, 24) = "13"
ns.Cells(ra, 25) = "6"
ns.Cells(ra, 26) = ""
ns.Cells(ra, 27) = ""
ns.Cells(ra, 28) = ""
ns.Cells(ra, 29) = ""
ns.Cells(ra, 30) = ""
ns.Cells(ra, 31) = ""
ns.Cells(ra, 32) = ""
ns.Cells(ra, 33) = ""
ns.Cells(ra, 34) = ""
ns.Cells(ra, 35) = ""
ns.Cells(ra, 36) = ""
ns.Cells(ra, 37) = ""
ns.Cells(ra, 38) = ""
ns.Cells(ra, 39) = ""
ns.Cells(ra, 40) = ""
ns.Cells(ra, 41) = ""
ns.Cells(ra, 42) = ""
ns.Cells(ra, 43) = ""
ns.Cells(ra, 44) = ""
ns.Cells(ra, 45) = ""
ns.Cells(ra, 46) = ""
ns.Cells(ra, 47) = ""
ns.Cells(ra, 48) = ""
ns.Cells(ra, 49) = ""
ns.Cells(ra, 50) = ""
ns.Cells(ra, 51) = ""
ns.Cells(ra, 52) = ""
ns.Cells(ra, 53) = ""
ns.Cells(ra, 54) = ""
ns.Cells(ra, 55) = ""
ns.Cells(ra, 56) = ""
ns.Cells(ra, 57) = ""
ns.Cells(ra, 58) = ""
ns.Cells(ra, 59) = ""
ns.Cells(ra, 60) = ""
ns.Cells(ra, 61) = PRSETPH358MPN
ns.Cells(ra, 62) = ""
ns.Cells(ra, 63) = ""
ns.Cells(ra, 64) = ""
ns.Cells(ra, 65) = ""
ns.Cells(ra, 66) = ""
ns.Cells(ra, 67) = ""
ns.Cells(ra, 68) = ""
ns.Cells(ra, 69) = ""

'4X6 HG SKU  - product row 5
ra = ra + 1
ns.Cells(ra, 1) = "SKU"
ns.Cells(ra, 2) = ""
ns.Cells(ra, 3) = ""
ns.Cells(ra, 4) = "[RT]Finishing Options=Pole Hem & Fringe,[RT]Flag and Pole Size=3' X 5' Flag with 8' Oak Pole"
ns.Cells(ra, 5) = ""
ns.Cells(ra, 6) = PRSETPHF358SKU
ns.Cells(ra, 7) = "FlagZone"
ns.Cells(ra, 8) = "FlagZone"
ns.Cells(ra, 9) = ""
ns.Cells(ra, 10) = ""
ns.Cells(ra, 11) = "FlagZone"
ns.Cells(ra, 12) = ""
ns.Cells(ra, 13) = ""
ns.Cells(ra, 14) = ""
ns.Cells(ra, 15) = ""
ns.Cells(ra, 16) = PRSETPHF358Cost
ns.Cells(ra, 17) = ""
ns.Cells(ra, 18) = ""
ns.Cells(ra, 19) = ""
ns.Cells(ra, 20) = "N"
ns.Cells(ra, 21) = ""
ns.Cells(ra, 22) = "18"
ns.Cells(ra, 23) = "53"
ns.Cells(ra, 24) = "13"
ns.Cells(ra, 25) = "6"
ns.Cells(ra, 26) = ""
ns.Cells(ra, 27) = ""
ns.Cells(ra, 28) = ""
ns.Cells(ra, 29) = ""
ns.Cells(ra, 30) = ""
ns.Cells(ra, 31) = ""
ns.Cells(ra, 32) = ""
ns.Cells(ra, 33) = ""
ns.Cells(ra, 34) = ""
ns.Cells(ra, 35) = ""
ns.Cells(ra, 36) = ""
ns.Cells(ra, 37) = ""
ns.Cells(ra, 38) = ""
ns.Cells(ra, 39) = ""
ns.Cells(ra, 40) = ""
ns.Cells(ra, 41) = ""
ns.Cells(ra, 42) = ""
ns.Cells(ra, 43) = ""
ns.Cells(ra, 44) = ""
ns.Cells(ra, 45) = ""
ns.Cells(ra, 46) = ""
ns.Cells(ra, 47) = ""
ns.Cells(ra, 48) = ""
ns.Cells(ra, 49) = ""
ns.Cells(ra, 50) = ""
ns.Cells(ra, 51) = ""
ns.Cells(ra, 52) = ""
ns.Cells(ra, 53) = ""
ns.Cells(ra, 54) = ""
ns.Cells(ra, 55) = ""
ns.Cells(ra, 56) = ""
ns.Cells(ra, 57) = ""
ns.Cells(ra, 58) = ""
ns.Cells(ra, 59) = ""
ns.Cells(ra, 60) = ""
ns.Cells(ra, 61) = PRSETPHF358MPN
ns.Cells(ra, 62) = ""
ns.Cells(ra, 63) = ""
ns.Cells(ra, 64) = ""
ns.Cells(ra, 65) = ""
ns.Cells(ra, 66) = ""
ns.Cells(ra, 67) = ""
ns.Cells(ra, 68) = ""
ns.Cells(ra, 69) = ""

'5X8 HG SKU  - product row 6
ra = ra + 1
ns.Cells(ra, 1) = "SKU"
ns.Cells(ra, 2) = ""
ns.Cells(ra, 3) = ""
ns.Cells(ra, 4) = "[RT]Finishing Options=Pole Hem Only,[RT]Flag and Pole Size=4' X 6' Flag with 9' Oak Pole"
ns.Cells(ra, 5) = ""
ns.Cells(ra, 6) = PRSETPH469SKU
ns.Cells(ra, 7) = "FlagZone"
ns.Cells(ra, 8) = "FlagZone"
ns.Cells(ra, 9) = ""
ns.Cells(ra, 10) = ""
ns.Cells(ra, 11) = "FlagZone"
ns.Cells(ra, 12) = ""
ns.Cells(ra, 13) = ""
ns.Cells(ra, 14) = ""
ns.Cells(ra, 15) = ""
ns.Cells(ra, 16) = PRSETPH469Cost
ns.Cells(ra, 17) = ""
ns.Cells(ra, 18) = ""
ns.Cells(ra, 19) = ""
ns.Cells(ra, 20) = "N"
ns.Cells(ra, 21) = ""
ns.Cells(ra, 22) = "25"
ns.Cells(ra, 23) = "53"
ns.Cells(ra, 24) = "13"
ns.Cells(ra, 25) = "6"
ns.Cells(ra, 26) = ""
ns.Cells(ra, 27) = ""
ns.Cells(ra, 28) = ""
ns.Cells(ra, 29) = ""
ns.Cells(ra, 30) = ""
ns.Cells(ra, 31) = ""
ns.Cells(ra, 32) = ""
ns.Cells(ra, 33) = ""
ns.Cells(ra, 34) = ""
ns.Cells(ra, 35) = ""
ns.Cells(ra, 36) = ""
ns.Cells(ra, 37) = ""
ns.Cells(ra, 38) = ""
ns.Cells(ra, 39) = ""
ns.Cells(ra, 40) = ""
ns.Cells(ra, 41) = ""
ns.Cells(ra, 42) = ""
ns.Cells(ra, 43) = ""
ns.Cells(ra, 44) = ""
ns.Cells(ra, 45) = ""
ns.Cells(ra, 46) = ""
ns.Cells(ra, 47) = ""
ns.Cells(ra, 48) = ""
ns.Cells(ra, 49) = ""
ns.Cells(ra, 50) = ""
ns.Cells(ra, 51) = ""
ns.Cells(ra, 52) = ""
ns.Cells(ra, 53) = ""
ns.Cells(ra, 54) = ""
ns.Cells(ra, 55) = ""
ns.Cells(ra, 56) = ""
ns.Cells(ra, 57) = ""
ns.Cells(ra, 58) = ""
ns.Cells(ra, 59) = ""
ns.Cells(ra, 60) = ""
ns.Cells(ra, 61) = PRSETPH469MPN
ns.Cells(ra, 62) = ""
ns.Cells(ra, 63) = ""
ns.Cells(ra, 64) = ""
ns.Cells(ra, 65) = ""
ns.Cells(ra, 66) = ""
ns.Cells(ra, 67) = ""
ns.Cells(ra, 68) = ""
ns.Cells(ra, 69) = ""

'6X10 HG SKU  - product row 7
ra = ra + 1
ns.Cells(ra, 1) = "SKU"
ns.Cells(ra, 2) = ""
ns.Cells(ra, 3) = ""
ns.Cells(ra, 4) = "[RT]Finishing Options=Pole Hem & Fringe,[RT]Flag and Pole Size=4' X 6' Flag with 9' Oak Pole"
ns.Cells(ra, 5) = ""
ns.Cells(ra, 6) = PRSETPHF469SKU
ns.Cells(ra, 7) = "FlagZone"
ns.Cells(ra, 8) = "FlagZone"
ns.Cells(ra, 9) = ""
ns.Cells(ra, 10) = ""
ns.Cells(ra, 11) = "FlagZone"
ns.Cells(ra, 12) = ""
ns.Cells(ra, 13) = ""
ns.Cells(ra, 14) = ""
ns.Cells(ra, 15) = ""
ns.Cells(ra, 16) = PRSETPHF469Cost
ns.Cells(ra, 17) = ""
ns.Cells(ra, 18) = ""
ns.Cells(ra, 19) = ""
ns.Cells(ra, 20) = "N"
ns.Cells(ra, 21) = ""
ns.Cells(ra, 22) = "25"
ns.Cells(ra, 23) = "53"
ns.Cells(ra, 24) = "13"
ns.Cells(ra, 25) = "6"
ns.Cells(ra, 26) = ""
ns.Cells(ra, 27) = ""
ns.Cells(ra, 28) = ""
ns.Cells(ra, 29) = ""
ns.Cells(ra, 30) = ""
ns.Cells(ra, 31) = ""
ns.Cells(ra, 32) = ""
ns.Cells(ra, 33) = ""
ns.Cells(ra, 34) = ""
ns.Cells(ra, 35) = ""
ns.Cells(ra, 36) = ""
ns.Cells(ra, 37) = ""
ns.Cells(ra, 38) = ""
ns.Cells(ra, 39) = ""
ns.Cells(ra, 40) = ""
ns.Cells(ra, 41) = ""
ns.Cells(ra, 42) = ""
ns.Cells(ra, 43) = ""
ns.Cells(ra, 44) = ""
ns.Cells(ra, 45) = ""
ns.Cells(ra, 46) = ""
ns.Cells(ra, 47) = ""
ns.Cells(ra, 48) = ""
ns.Cells(ra, 49) = ""
ns.Cells(ra, 50) = ""
ns.Cells(ra, 51) = ""
ns.Cells(ra, 52) = ""
ns.Cells(ra, 53) = ""
ns.Cells(ra, 54) = ""
ns.Cells(ra, 55) = ""
ns.Cells(ra, 56) = ""
ns.Cells(ra, 57) = ""
ns.Cells(ra, 58) = ""
ns.Cells(ra, 59) = ""
ns.Cells(ra, 60) = ""
ns.Cells(ra, 61) = PRSETPHF469MPN
ns.Cells(ra, 62) = ""
ns.Cells(ra, 63) = ""
ns.Cells(ra, 64) = ""
ns.Cells(ra, 65) = ""
ns.Cells(ra, 66) = ""
ns.Cells(ra, 67) = ""
ns.Cells(ra, 68) = ""
ns.Cells(ra, 69) = ""
End Sub

Sub FlagSKURules(ns As Worksheet, ra As Long)  ' ra is first row of each set of product data

'12inX18inHG Rule - product row 8
ra = ra + 7
ns.Cells(ra, 1) = "RULE"
ns.Cells(ra, 2) = ""
ns.Cells(ra, 3) = ""
ns.Cells(ra, 4) = ""
ns.Cells(ra, 5) = ""
ns.Cells(ra, 6) = PRSETPH357SKU
ns.Cells(ra, 7) = ""
ns.Cells(ra, 8) = ""
ns.Cells(ra, 9) = ""
ns.Cells(ra, 10) = ""
ns.Cells(ra, 11) = ""
ns.Cells(ra, 12) = ""
ns.Cells(ra, 13) = ""
ns.Cells(ra, 14) = ""
ns.Cells(ra, 15) = PRSETPH357Price
ns.Cells(ra, 16) = ""
ns.Cells(ra, 17) = ""
ns.Cells(ra, 18) = ""
ns.Cells(ra, 19) = ""
ns.Cells(ra, 20) = ""
ns.Cells(ra, 21) = ""
ns.Cells(ra, 22) = ""
ns.Cells(ra, 23) = ""
ns.Cells(ra, 24) = ""
ns.Cells(ra, 25) = ""
ns.Cells(ra, 26) = "Y"
ns.Cells(ra, 27) = "Y"
ns.Cells(ra, 28) = ""
ns.Cells(ra, 29) = ""
ns.Cells(ra, 30) = ""
ns.Cells(ra, 31) = ""
ns.Cells(ra, 32) = ""
ns.Cells(ra, 33) = "https://emflag.com/content/Flags/State/Indoor/Presentation%20Sets/PRSET-" + state + "-PH.png"
ns.Cells(ra, 34) = "https://emflag.com/content/Flags/State/Indoor/Presentation%20Sets/PRSET-" + state + "-PH.png"
ns.Cells(ra, 35) = ""
ns.Cells(ra, 36) = ""
ns.Cells(ra, 37) = ""
ns.Cells(ra, 38) = "N"
ns.Cells(ra, 39) = ""
ns.Cells(ra, 40) = ""
ns.Cells(ra, 41) = ""
ns.Cells(ra, 42) = ""
ns.Cells(ra, 43) = ""
ns.Cells(ra, 44) = ""
ns.Cells(ra, 45) = ""
ns.Cells(ra, 46) = ""
ns.Cells(ra, 47) = ""
ns.Cells(ra, 48) = ""
ns.Cells(ra, 49) = ""
ns.Cells(ra, 50) = ""
ns.Cells(ra, 51) = ""
ns.Cells(ra, 52) = ""
ns.Cells(ra, 53) = ""
ns.Cells(ra, 54) = ""
ns.Cells(ra, 55) = ""
ns.Cells(ra, 56) = ""
ns.Cells(ra, 57) = ""
ns.Cells(ra, 58) = ""
ns.Cells(ra, 59) = ""
ns.Cells(ra, 60) = ""
ns.Cells(ra, 61) = ""
ns.Cells(ra, 62) = ""
ns.Cells(ra, 63) = ""
ns.Cells(ra, 64) = ""
ns.Cells(ra, 65) = ""
ns.Cells(ra, 66) = ""
ns.Cells(ra, 67) = ""
ns.Cells(ra, 68) = ""
ns.Cells(ra, 69) = ""

'2X3 HG Rule - product row 9
ra = ra + 1
ns.Cells(ra, 1) = "RULE"
ns.Cells(ra, 2) = ""
ns.Cells(ra, 3) = ""
ns.Cells(ra, 4) = ""
ns.Cells(ra, 5) = ""
ns.Cells(ra, 6) = PRSETPHF357SKU
ns.Cells(ra, 7) = ""
ns.Cells(ra, 8) = ""
ns.Cells(ra, 9) = ""
ns.Cells(ra, 10) = ""
ns.Cells(ra, 11) = ""
ns.Cells(ra, 12) = ""
ns.Cells(ra, 13) = ""
ns.Cells(ra, 14) = ""
ns.Cells(ra, 15) = PRSETPHF357Price
ns.Cells(ra, 16) = ""
ns.Cells(ra, 17) = ""
ns.Cells(ra, 18) = ""
ns.Cells(ra, 19) = ""
ns.Cells(ra, 20) = ""
ns.Cells(ra, 21) = ""
ns.Cells(ra, 22) = ""
ns.Cells(ra, 23) = ""
ns.Cells(ra, 24) = ""
ns.Cells(ra, 25) = ""
ns.Cells(ra, 26) = "Y"
ns.Cells(ra, 27) = "Y"
ns.Cells(ra, 28) = ""
ns.Cells(ra, 29) = ""
ns.Cells(ra, 30) = ""
ns.Cells(ra, 31) = ""
ns.Cells(ra, 32) = ""
ns.Cells(ra, 33) = "https://emflag.com/content/Flags/State/Indoor/Presentation%20Sets/PRSET-" + state + "-PHF.png"
ns.Cells(ra, 34) = "https://emflag.com/content/Flags/State/Indoor/Presentation%20Sets/PRSET-" + state + "-PHF.png"
ns.Cells(ra, 35) = ""
ns.Cells(ra, 36) = ""
ns.Cells(ra, 37) = ""
ns.Cells(ra, 38) = "N"
ns.Cells(ra, 39) = ""
ns.Cells(ra, 40) = ""
ns.Cells(ra, 41) = ""
ns.Cells(ra, 42) = ""
ns.Cells(ra, 43) = ""
ns.Cells(ra, 44) = ""
ns.Cells(ra, 45) = ""
ns.Cells(ra, 46) = ""
ns.Cells(ra, 47) = ""
ns.Cells(ra, 48) = ""
ns.Cells(ra, 49) = ""
ns.Cells(ra, 50) = ""
ns.Cells(ra, 51) = ""
ns.Cells(ra, 52) = ""
ns.Cells(ra, 53) = ""
ns.Cells(ra, 54) = ""
ns.Cells(ra, 55) = ""
ns.Cells(ra, 56) = ""
ns.Cells(ra, 57) = ""
ns.Cells(ra, 58) = ""
ns.Cells(ra, 59) = ""
ns.Cells(ra, 60) = ""
ns.Cells(ra, 61) = ""
ns.Cells(ra, 62) = ""
ns.Cells(ra, 63) = ""
ns.Cells(ra, 64) = ""
ns.Cells(ra, 65) = ""
ns.Cells(ra, 66) = ""
ns.Cells(ra, 67) = ""
ns.Cells(ra, 68) = ""
ns.Cells(ra, 69) = ""

'3X5 HG Rule - product row 10
ra = ra + 1
ns.Cells(ra, 1) = "RULE"
ns.Cells(ra, 2) = ""
ns.Cells(ra, 3) = ""
ns.Cells(ra, 4) = ""
ns.Cells(ra, 5) = ""
ns.Cells(ra, 6) = PRSETPH358SKU
ns.Cells(ra, 7) = ""
ns.Cells(ra, 8) = ""
ns.Cells(ra, 9) = ""
ns.Cells(ra, 10) = ""
ns.Cells(ra, 11) = ""
ns.Cells(ra, 12) = ""
ns.Cells(ra, 13) = ""
ns.Cells(ra, 14) = ""
ns.Cells(ra, 15) = PRSETPH358Price
ns.Cells(ra, 16) = ""
ns.Cells(ra, 17) = ""
ns.Cells(ra, 18) = ""
ns.Cells(ra, 19) = ""
ns.Cells(ra, 20) = ""
ns.Cells(ra, 21) = ""
ns.Cells(ra, 22) = ""
ns.Cells(ra, 23) = ""
ns.Cells(ra, 24) = ""
ns.Cells(ra, 25) = ""
ns.Cells(ra, 26) = "Y"
ns.Cells(ra, 27) = "Y"
ns.Cells(ra, 28) = ""
ns.Cells(ra, 29) = ""
ns.Cells(ra, 30) = ""
ns.Cells(ra, 31) = ""
ns.Cells(ra, 32) = ""
ns.Cells(ra, 33) = "https://emflag.com/content/Flags/State/Indoor/Presentation%20Sets/PRSET-" + state + "-PH.png"
ns.Cells(ra, 34) = "https://emflag.com/content/Flags/State/Indoor/Presentation%20Sets/PRSET-" + state + "-PH.png"
ns.Cells(ra, 35) = ""
ns.Cells(ra, 36) = ""
ns.Cells(ra, 37) = ""
ns.Cells(ra, 38) = "N"
ns.Cells(ra, 39) = ""
ns.Cells(ra, 40) = ""
ns.Cells(ra, 41) = ""
ns.Cells(ra, 42) = ""
ns.Cells(ra, 43) = ""
ns.Cells(ra, 44) = ""
ns.Cells(ra, 45) = ""
ns.Cells(ra, 46) = ""
ns.Cells(ra, 47) = ""
ns.Cells(ra, 48) = ""
ns.Cells(ra, 49) = ""
ns.Cells(ra, 50) = ""
ns.Cells(ra, 51) = ""
ns.Cells(ra, 52) = ""
ns.Cells(ra, 53) = ""
ns.Cells(ra, 54) = ""
ns.Cells(ra, 55) = ""
ns.Cells(ra, 56) = ""
ns.Cells(ra, 57) = ""
ns.Cells(ra, 58) = ""
ns.Cells(ra, 59) = ""
ns.Cells(ra, 60) = ""
ns.Cells(ra, 61) = ""
ns.Cells(ra, 62) = ""
ns.Cells(ra, 63) = ""
ns.Cells(ra, 64) = ""
ns.Cells(ra, 65) = ""
ns.Cells(ra, 66) = ""
ns.Cells(ra, 67) = ""
ns.Cells(ra, 68) = ""
ns.Cells(ra, 69) = ""

'4X6 HG Rule  - product row 11
ra = ra + 1
ns.Cells(ra, 1) = "RULE"
ns.Cells(ra, 2) = ""
ns.Cells(ra, 3) = ""
ns.Cells(ra, 4) = ""
ns.Cells(ra, 5) = ""
ns.Cells(ra, 6) = PRSETPHF358SKU
ns.Cells(ra, 7) = ""
ns.Cells(ra, 8) = ""
ns.Cells(ra, 9) = ""
ns.Cells(ra, 10) = ""
ns.Cells(ra, 11) = ""
ns.Cells(ra, 12) = ""
ns.Cells(ra, 13) = ""
ns.Cells(ra, 14) = ""
ns.Cells(ra, 15) = PRSETPHF358Price
ns.Cells(ra, 16) = ""
ns.Cells(ra, 17) = ""
ns.Cells(ra, 18) = ""
ns.Cells(ra, 19) = ""
ns.Cells(ra, 20) = ""
ns.Cells(ra, 21) = ""
ns.Cells(ra, 22) = ""
ns.Cells(ra, 23) = ""
ns.Cells(ra, 24) = ""
ns.Cells(ra, 25) = ""
ns.Cells(ra, 26) = "Y"
ns.Cells(ra, 27) = "Y"
ns.Cells(ra, 28) = ""
ns.Cells(ra, 29) = ""
ns.Cells(ra, 30) = ""
ns.Cells(ra, 31) = ""
ns.Cells(ra, 32) = ""
ns.Cells(ra, 33) = "https://emflag.com/content/Flags/State/Indoor/Presentation%20Sets/PRSET-" + state + "-PHF.png"
ns.Cells(ra, 34) = "https://emflag.com/content/Flags/State/Indoor/Presentation%20Sets/PRSET-" + state + "-PHF.png"
ns.Cells(ra, 35) = ""
ns.Cells(ra, 36) = ""
ns.Cells(ra, 37) = ""
ns.Cells(ra, 38) = "N"
ns.Cells(ra, 39) = ""
ns.Cells(ra, 40) = ""
ns.Cells(ra, 41) = ""
ns.Cells(ra, 42) = ""
ns.Cells(ra, 43) = ""
ns.Cells(ra, 44) = ""
ns.Cells(ra, 45) = ""
ns.Cells(ra, 46) = ""
ns.Cells(ra, 47) = ""
ns.Cells(ra, 48) = ""
ns.Cells(ra, 49) = ""
ns.Cells(ra, 50) = ""
ns.Cells(ra, 51) = ""
ns.Cells(ra, 52) = ""
ns.Cells(ra, 53) = ""
ns.Cells(ra, 54) = ""
ns.Cells(ra, 55) = ""
ns.Cells(ra, 56) = ""
ns.Cells(ra, 57) = ""
ns.Cells(ra, 58) = ""
ns.Cells(ra, 59) = ""
ns.Cells(ra, 60) = ""
ns.Cells(ra, 61) = ""
ns.Cells(ra, 62) = ""
ns.Cells(ra, 63) = ""
ns.Cells(ra, 64) = ""
ns.Cells(ra, 65) = ""
ns.Cells(ra, 66) = ""
ns.Cells(ra, 67) = ""
ns.Cells(ra, 68) = ""
ns.Cells(ra, 69) = ""

'5X8 HG Rule  - product row 12
ra = ra + 1
ns.Cells(ra, 1) = "RULE"
ns.Cells(ra, 2) = ""
ns.Cells(ra, 3) = ""
ns.Cells(ra, 4) = ""
ns.Cells(ra, 5) = ""
ns.Cells(ra, 6) = PRSETPH469SKU
ns.Cells(ra, 7) = ""
ns.Cells(ra, 8) = ""
ns.Cells(ra, 9) = ""
ns.Cells(ra, 10) = ""
ns.Cells(ra, 11) = ""
ns.Cells(ra, 12) = ""
ns.Cells(ra, 13) = ""
ns.Cells(ra, 14) = ""
ns.Cells(ra, 15) = PRSETPH469Price
ns.Cells(ra, 16) = ""
ns.Cells(ra, 17) = ""
ns.Cells(ra, 18) = ""
ns.Cells(ra, 19) = ""
ns.Cells(ra, 20) = ""
ns.Cells(ra, 21) = ""
ns.Cells(ra, 22) = ""
ns.Cells(ra, 23) = ""
ns.Cells(ra, 24) = ""
ns.Cells(ra, 25) = ""
ns.Cells(ra, 26) = "Y"
ns.Cells(ra, 27) = "Y"
ns.Cells(ra, 28) = ""
ns.Cells(ra, 29) = ""
ns.Cells(ra, 30) = ""
ns.Cells(ra, 31) = ""
ns.Cells(ra, 32) = ""
ns.Cells(ra, 33) = "https://emflag.com/content/Flags/State/Indoor/Presentation%20Sets/PRSET-" + state + "-PH.png"
ns.Cells(ra, 34) = "https://emflag.com/content/Flags/State/Indoor/Presentation%20Sets/PRSET-" + state + "-PH.png"
ns.Cells(ra, 35) = ""
ns.Cells(ra, 36) = ""
ns.Cells(ra, 37) = ""
ns.Cells(ra, 38) = "N"
ns.Cells(ra, 39) = ""
ns.Cells(ra, 40) = ""
ns.Cells(ra, 41) = ""
ns.Cells(ra, 42) = ""
ns.Cells(ra, 43) = ""
ns.Cells(ra, 44) = ""
ns.Cells(ra, 45) = ""
ns.Cells(ra, 46) = ""
ns.Cells(ra, 47) = ""
ns.Cells(ra, 48) = ""
ns.Cells(ra, 49) = ""
ns.Cells(ra, 50) = ""
ns.Cells(ra, 51) = ""
ns.Cells(ra, 52) = ""
ns.Cells(ra, 53) = ""
ns.Cells(ra, 54) = ""
ns.Cells(ra, 55) = ""
ns.Cells(ra, 56) = ""
ns.Cells(ra, 57) = ""
ns.Cells(ra, 58) = ""
ns.Cells(ra, 59) = ""
ns.Cells(ra, 60) = ""
ns.Cells(ra, 61) = ""
ns.Cells(ra, 62) = ""
ns.Cells(ra, 63) = ""
ns.Cells(ra, 64) = ""
ns.Cells(ra, 65) = ""
ns.Cells(ra, 66) = ""
ns.Cells(ra, 67) = ""
ns.Cells(ra, 68) = ""
ns.Cells(ra, 69) = ""

'6X10 HG Rule  - product row 13
ra = ra + 1
ns.Cells(ra, 1) = "RULE"
ns.Cells(ra, 2) = ""
ns.Cells(ra, 3) = ""
ns.Cells(ra, 4) = ""
ns.Cells(ra, 5) = ""
ns.Cells(ra, 6) = PRSETPHF469SKU
ns.Cells(ra, 7) = ""
ns.Cells(ra, 8) = ""
ns.Cells(ra, 9) = ""
ns.Cells(ra, 10) = ""
ns.Cells(ra, 11) = ""
ns.Cells(ra, 12) = ""
ns.Cells(ra, 13) = ""
ns.Cells(ra, 14) = ""
ns.Cells(ra, 15) = PRSETPHF469Price
ns.Cells(ra, 16) = ""
ns.Cells(ra, 17) = ""
ns.Cells(ra, 18) = ""
ns.Cells(ra, 19) = ""
ns.Cells(ra, 20) = ""
ns.Cells(ra, 21) = ""
ns.Cells(ra, 22) = ""
ns.Cells(ra, 23) = ""
ns.Cells(ra, 24) = ""
ns.Cells(ra, 25) = ""
ns.Cells(ra, 26) = "Y"
ns.Cells(ra, 27) = "Y"
ns.Cells(ra, 28) = ""
ns.Cells(ra, 29) = ""
ns.Cells(ra, 30) = ""
ns.Cells(ra, 31) = ""
ns.Cells(ra, 32) = ""
ns.Cells(ra, 33) = "https://emflag.com/content/Flags/State/Indoor/Presentation%20Sets/PRSET-" + state + "-PHF.png"
ns.Cells(ra, 34) = "https://emflag.com/content/Flags/State/Indoor/Presentation%20Sets/PRSET-" + state + "-PHF.png"
ns.Cells(ra, 35) = ""
ns.Cells(ra, 36) = ""
ns.Cells(ra, 37) = ""
ns.Cells(ra, 38) = "N"
ns.Cells(ra, 39) = ""
ns.Cells(ra, 40) = ""
ns.Cells(ra, 41) = ""
ns.Cells(ra, 42) = ""
ns.Cells(ra, 43) = ""
ns.Cells(ra, 44) = ""
ns.Cells(ra, 45) = ""
ns.Cells(ra, 46) = ""
ns.Cells(ra, 47) = ""
ns.Cells(ra, 48) = ""
ns.Cells(ra, 49) = ""
ns.Cells(ra, 50) = ""
ns.Cells(ra, 51) = ""
ns.Cells(ra, 52) = ""
ns.Cells(ra, 53) = ""
ns.Cells(ra, 54) = ""
ns.Cells(ra, 55) = ""
ns.Cells(ra, 56) = ""
ns.Cells(ra, 57) = ""
ns.Cells(ra, 58) = ""
ns.Cells(ra, 59) = ""
ns.Cells(ra, 60) = ""
ns.Cells(ra, 61) = ""
ns.Cells(ra, 62) = ""
ns.Cells(ra, 63) = ""
ns.Cells(ra, 64) = ""
ns.Cells(ra, 65) = ""
ns.Cells(ra, 66) = ""
ns.Cells(ra, 67) = ""
ns.Cells(ra, 68) = ""
ns.Cells(ra, 69) = ""
End Sub

